### ISSUE TITLE
feature suggestion: import of packing list files

### ISSUE THREAD

**Issue by code-surfer** [nbossard/packlist#20] opened 2016-03-20 19:42 UTC
I've got a packing list in a text file. It would be nice if I could import it into packlist. (I don't want to type it in again, especially not a smartphone's virtual keyboard.)

(I've actually managed to import it, by finding the PREFS.xml, and exchanging its JSON payload with one I created with a few lines of javascript from the packing list text file I had. Nice hacking exercise, but not recommended for regular use...)

**Comment by nbossard** [comment] 2016-03-20 20:53
Good job...
Yes it is a bit complicated for future million of users :-)
Well storage in pref files is just a dumb easy to write  implementation implementing ISavingModule.
I plan to use a bit more efficient implementation when lists will begin to grow.
So I DO need an import functionnality...

**Comment by nbossard** [comment] 2016-04-07 15:40
Added, Will be available in incoming release 0.8

**Comment by nbossard** [comment] 2016-04-09 13:47
Hello code-surfer,
I have added most of what you suggested in release 0.8. (available since today 9th of april).
Please have a look.
Best regards, Nicolas

**Comment by anarcat** [comment] 2016-04-11 03:50
just discovering the app - it's great!

i am wondering if this could be extended to export from a website or a specific URL?

i use the following list as the mother of all packing lists for my trips: https://anarc.at/pleinair/liste/

it's more or less markdown in the back: http://src.anarc.at/wikis/anarc.at.git/blob_plain/HEAD:/pleinair/liste.mdwn

my process, usually, is to jot down items from that mega list on a piece of paper, then check the items as I pack them. it'd be interesting to reproduce that workflow here!

**Comment by nbossard** [comment] 2016-04-11 13:18
Hello @anarcat
I copied paste from the website you suggested into mass import screen of packlist, worked fine :-)

I start working on pre-saved list functionality that you can add or not as a whole to your next trip depending on what you are planning to do.
But may be add item by item and not only full list ??
See issue #8

**Comment by anarcat** [comment] 2016-04-11 14:26
yes, #8 covers part of what i am looking for: if the headers could be parsed to make categories, that would be great.

my idea of such an interface would be that there would be the "great list" and i would "swipe" things off of it that i don't need to make a list for the event that i need.

**Comment by anarcat** [comment] 2016-04-11 14:26
ah, and of course, if the app could talk directly through HTTP that would be great. not sure how i would go around copy-pasting a whole page like what you did...

**Comment by code-surfer** [comment] 2016-04-12 07:11
After f-droid still didn't offer me the update (it's set to update daily), I ran an "update repos" manually and got the 0.8.

I think this new import feature is a good start! I simply did a "select all" in an email, pasted it into the packlist form and it worked.
It's just that people who'd like to use the item weight feature can't get them from this form (as it's currently implemented).
I wonder what the typical use case would be.
Before you implemented it, I wondered about a simple web page where people could enter their items, perhaps change their order and then download the list from the packlist app.
And of course upload, modify, download.

So far, I haven't had weights in my lists, but I like the idea.

**Comment by nbossard** [comment] 2016-04-18 08:30
Helllo @code-surfer do you think it would be useful to add a text format supporting an optional weight like this 

> books (500)
> socks (50)
> raincoat (850)
> trousers

**Comment by code-surfer** [comment] 2016-04-18 20:29
I'm not really the right one to ask -- I can easily get any format I prefer into any plain text format you chose. :-)
I'm not sure what less technically inclined people are likely to prefer. I guess many will have existing packing lists in spreadsheets. (Unlike most people I hardly ever use such programs.) Looking at LibreOffice Calc's supported formats, the simplest one is probably gonna be CSV. But it may be too simple, not providing any obvious choice for categories (#8).

If you can easily support [markdown](http://daringfireball.net/projects/markdown/), then turning any header into a category and any list item into a packlist item may be a good way to go. Use of a library would be recommended, as e.g. headers come in several forms:

```
# this is one

this is also a header
===
```

My favorite would be something explicit like JSON, but most people would probably have major trouble getting their packlists into this format... (one typo and a JSON parser will reject it)

```
{ "groups": [ { "category": "Camping", "items": [ { "name": "tent", "weight": 1500 }, { "name": "sleeping bag" } ] } ] }
```

**Comment by nbossard** [comment] 2016-08-06 21:19
We now have a quiet complete import of basic list or more complex format lists / trips in packlist.
I close this quiet old topic and we can open a new one for additional discussion if useful.
Thanks for your suggestions.

**Closed as completed by nbossard** 2016-08-06 21:19 UTC
Labels: enhancement
